# Generated by Django 5.2.17 on 2026-09-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('formal', 'Pendidikan Formal'), ('informal', 'Pendidikan Informal & Sertifikasi')], default='formal', max_length=20)),
                ('year', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
