# Generated by Django 5.2.17 on 2026-09-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_education_category_alter_education_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
